# Use a slim Python base image
FROM python:3.10-slim

# Set environment variables for virtual environment
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Create the virtual environment (don't install anything yet)
RUN python -m venv --copies $VIRTUAL_ENV

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies using pip
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip && \
    pip install -r requirements.txt
